"""Initialization for Attributes module"""
from .attribute import Attribute
from .attribute_credit_card import CreditCard
from .attribute_id_card import IDCard
from .attribute_name_surname import NameSurname
from .attribute_num_days import NumDays
from .attribute_phone_number import PhoneNumber
from .attribute_room_type import RoomType
from .attribute_arrival_date import ArrivalDate
from .attribute_localizer import Localizer
from .attribute_room_key import RoomKey
